apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-volume
  namespace: default
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 100Gi
  accesModes:
    - ReadWriteOnce
  storageClassName: manual
  local:
    path: "/var/lib/postgresql/data"