##
## EPITECH PROJECT, 2018
## 
## File description:
## 
##

all:
	cp challenge1/hex_to_base64.py challenge01
	cp challenge2/fixed_xor.py challenge02
	cp challenge3/single_byte_xor-cypher.py challenge03
	cp challenge4/detect_single-byte_xor.py challenge04
	cp challenge5/repeating_key_xop.py challenge05
	chmod 777 challenge01
	chmod 777 challenge02
	chmod 777 challenge03
	chmod 777 challenge04
	chmod 777 challenge05

clean:
	rm challenge*

fclean:
	rm challenge*

re: fclean all
