##
## EPITECH PROJECT, 2017
## Makefile dop_op
## File description:
## Makefile do op
##

SRC	=	do_op.c
OBJ	=	$(SRC:.c=.o)

all:
	gcc $(SRC) -L../lib -lmy

clean:
	rm -f *.o
	rm -f *~

fclean: clean

re: fclean all
