version: "3.8"
services:
  poll:
    build: ./poll
    ports:
      - 5000:80
    environment:
      - DEBUG
    networks:
      - poll-tier
    restart:
      always

  result:
    build: ./result
    ports:
      - 5001:80
    environment:
      - DEBUG
    networks:
      - result-tier
    restart:
      always

  worker:
    build: ./worker
    environment:
      - DEBUG
    networks:
      - back-tier
    restart:
      always

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - poll-tier
      - back-tier
    restart:
      always


  db:
    image: postgres:9.5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - result-tier
      - back-tier
    restart:
      always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: